# Generated by Django 4.2.9 on 2024-02-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('begu', '0007_alter_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.JSONField(default=dict),
        ),
    ]
