# Generated by Django 5.0.1 on 2024-02-26 14:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('begu', '0007_alter_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, null=True, size=None, verbose_name='sizes'),
        ),
    ]
